Removes double backslash in affiliate link
railslove/rcvr-api pull request #124
Opened 2021-05-25 11:15 UTC by bitboxer

Fixes https://github.com/railslove/recover-backlog/issues/145

2021-05-25 11:54 UTC, bonflintstone reviewed
But I just wanna be pedantic and say that you are chomping slashes, and not backslashes :grin:

2021-05-25 14:10 UTC, bitboxer commented
@bonflintstone Haha, yes. You are right. I just copied the wording from @koos . Fixed the commit message and ticket.

2021-05-25 15:54 UTC, salimhb requested changes
Also don't want to be pedantic, but this looks like overkill. This is not use input. We should just take care of setting the environment variable correctly!
Since we're using `URI` here, I also wrote a suggestion that should cover this without requiring the manual string manipulation.

2021-05-25 15:54 UTC, salimhb commented on app/models/affiliate.rb
> +    URI("#{(ENV['FRONTEND_URL'] || "").chomp("/")}/business/setup/intro").tap do |uri|
```suggestion
    URI(ENV['FRONTEND_URL'] || "").tap do |uri|
      uri.path = "/business/setup/intro"
```

2021-05-25 20:01 UTC, bitboxer commented on app/models/affiliate.rb
> +    URI("#{(ENV['FRONTEND_URL'] || "").chomp("/")}/business/setup/intro").tap do |uri|
Your suggestion only works if the path where the app is hosted is `/`, I thought of this, but I preferred the string version to not create this edge case. And yes, you could argue that setting the env variable correctly should also fix this, but since it is easy to create that settings mistake having this here will not harm anyone.

2021-05-25 20:02 UTC, bitboxer commented on app/models/affiliate.rb
> +    URI("#{(ENV['FRONTEND_URL'] || "").chomp("/")}/business/setup/intro").tap do |uri|
Also this "/" is a common thing I saw in a lot of apps where the URL is configurable. And this was the most flexible way.

2021-05-26 06:22 UTC, salimhb commented on app/models/affiliate.rb
> +    URI("#{(ENV['FRONTEND_URL'] || "").chomp("/")}/business/setup/intro").tap do |uri|
I'm convinced :)

2021-05-26 06:22 UTC, salimhb approved these changes

2021-05-26 08:18 UTC, merged