Added company count to the affiliate backend
railslove/rcvr-api pull request #126
Opened 2021-05-26 13:33 UTC by bitboxer

Closes https://github.com/railslove/recover-backlog/issues/152

2021-05-27 06:29 UTC, salimhb requested changes
virtual fields should me marked as readonly, otherwise they will show up as editable in RailsAdmin. This prevents us from saving an Affiliate as it tries to update these non-existing fields.
<img width="615" alt="image" src="https://user-images.githubusercontent.com/1375839/119776747-9bffcf00-bec5-11eb-9b5d-84944bea161a.png">

2021-05-27 06:29 UTC, salimhb commented on app/models/concerns/rails_admin_config/for_affiliate.rb
> +          end
```suggestion
          end
          read_only true
```

2021-05-27 06:29 UTC, salimhb commented on app/models/concerns/rails_admin_config/for_affiliate.rb
>            end
```suggestion
          end
          read_only true
```

2021-05-27 07:13 UTC, bitboxer commented
> virtual fields should me marked as readonly, otherwise they will show up as editable in RailsAdmin. This prevents us from saving an Affiliate as it tries to update these non-existing fields.

Oh, sorry. Totally forgot that part. Thanks for finding it.

2021-06-07 16:33 UTC, salimhb approved these changes

2021-06-07 16:37 UTC, merged