add possibility to customize the name of the menu (Issue: #155)
railslove/rcvr-api pull request #140
Opened 2021-07-08 12:17 UTC by niklas573

Backendwise I added a new attribute in the companies tab for the menu alias. I noticed that there already was one for the owner but setting the menu Alias on companies was more suitable in my opinion. This attribute is also delegated to the area entity to also provide the menu name when a user is checking in

2021-07-08 12:25 UTC, salimhb requested changes
What's the plan for migrating existing values of `menu_alias` from the `Owner` model?

2021-07-08 12:25 UTC, salimhb commented on db/schema.rb
> +    t.integer "cwa_checked_in"
This comes from https://github.com/railslove/rcvr-api/pull/138, it shouldn't be in this PR.

2021-07-08 12:25 UTC, salimhb commented on db/schema.rb
> +    t.string "menu_alias", default: "f"
The column didn't have a default value previously. Why "f" as default value now?

2021-07-08 13:03 UTC, niklas573 commented on db/schema.rb
> +    t.string "menu_alias", default: "f"
Was a result of a failed migration i think, thanks for noticing

2021-07-08 13:09 UTC, niklas573 commented
> What's the plan for migrating existing values of `menu_alias` from the `Owner` model?

I don't think that is necessary because there was no option for the user to add a menu alias at all, so all records should have no value for menu alias. Howerver, we should check first if there are any records with an existing value for menu alias in our production database. If thats the case i will think about how to migrate them

2021-07-08 13:11 UTC, niklas573 commented on db/schema.rb
> +    t.integer "cwa_checked_in"
Done

2021-07-12 08:26 UTC, niklas573 commented
> What's the plan for migrating existing values of `menu_alias` from the `Owner` model?
Pleas look at commit https://github.com/railslove/rcvr-api/pull/140/commits/52e29880f6b3a859a62489b606d353a6ccb86a41

2021-07-12 09:31 UTC, merged