Public URL with Checkin Statistics
railslove/rcvr-api pull request #39
Opened 2020-08-27 09:21 UTC by salimhb

https://trello.com/c/yg81s70e

Returns
```
[
  {
    "area_name": "Bedroom",
    "checkin_count": 3
  },
  {
    "area_name": "test",
    "checkin_count": 1
  }
]
```

2020-08-27 10:38 UTC, bonflintstone requested changes

2020-08-27 10:38 UTC, bonflintstone commented on app/controllers/owners/companies_controller.rb
> +    before_action :authenticate_owner!, except: %i[stats]
So I think we should have some kind of authentication, one possible solution was to give them a custom token we set in the admin, or perhaps to use the normal authentication. But completely open is not really a good idea for all the other companies I believe

2020-08-27 10:38 UTC, bonflintstone commented on app/controllers/owners/companies_controller.rb
> +        { area_name: a.name, checkin_count: a.tickets.open.count }
```suggestion
      stats = company.areas.map do |area|
        { area_name: area.name, checkin_count: area.tickets.open.count }
```
I really prefer non-single-char variable names :smile:

2020-08-27 15:20 UTC, salimhb commented on config/credentials.yml.enc
> +xoiesKdGgN4GkiHNrLNqhSbEjSp9stspi722YKgaA1IcNEH1ZsAlR4QDDcda9putqlbA4zKulyo3oVb1UzzShh5Rop46hGvWw/EyFyda9OcqYgcQPhMj6n2LWHD81cnwKba46lQqXcUC0kRaCXD2fwd5rtjYa/3G9CbqiWfDi0uAPVD01dAEfss1TP4W3G9QJXyCpi3
Turns out that secret_key_base is needed to create migrations 😄

2020-08-28 08:45 UTC, bonflintstone approved these changes
Super nice :+1: 

![](https://media2.giphy.com/media/icPn4EwqNpAsZQmInZ/giphy.gif)

2020-08-28 08:45 UTC, bonflintstone commented on spec/requests/owners/companies_request_spec.rb
> +RSpec.describe Owners::CompaniesController, type: :request do
Is it not configured to automatically infer the type from the folder?

2020-08-28 08:50 UTC, salimhb commented on spec/requests/owners/companies_request_spec.rb
> +RSpec.describe Owners::CompaniesController, type: :request do
It should, but I kept getting an error when I accessed `headers` below!

2020-08-28 09:00 UTC, endverbraucher approved these changes
Looks good to me!

![](https://media1.giphy.com/media/j2T7u14Xchv4AZRvuj/giphy.gif)

2020-08-28 09:35 UTC, salimhb commented on spec/requests/owners/companies_request_spec.rb
> +RSpec.describe Owners::CompaniesController, type: :request do
welp, I tried again and it worked!

2020-08-28 09:36 UTC, merged