🐛 Fix removing menu pdf
railslove/rcvr-api pull request #50
Opened 2020-11-06 14:41 UTC by m0ppers

first version was quickly made up but a big hack. after much googling and trying out stuff this finally looks like a railsy solution (first time ever rails :S)

please feedback if this is idiomatic

2020-11-06 14:42 UTC, m0ppers commented
fixes https://github.com/railslove/recover-backlog/issues/8

2020-11-10 09:39 UTC, m0ppers commented
added some simple tests...please check :thinking:

2020-11-10 10:30 UTC, salimhb requested changes

2020-11-10 10:30 UTC, salimhb commented on spec/models/company_spec.rb
> +      expect(company.menu_pdf_link).to be_nil
You can use the [change matcher](https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/built-in-matchers/change-matcher)
```suggestion
      expect { company.update!({:remove_menu_pdf => '1'}) }.to change { company.menu_pdf.blank? }.from(false).to(true)
      expect { company.update!({:remove_menu_pdf => '1'}) }.to change { company.menu_pdf_link }.to(nil)
```

2020-11-11 09:42 UTC, salimhb commented
/sem-approve

2020-11-11 10:56 UTC, salimhb approved these changes
![](https://media3.giphy.com/media/VD4Bt6FyYWcWj0LzDK/giphy.gif)

2020-11-18 21:21 UTC, merged