✨ inherit free usage from affiliate
railslove/rcvr-api pull request #60
Opened 2021-02-24 16:09 UTC by m0ppers

fixes https://github.com/railslove/recover-backlog/issues/91

I don't get why there is this menu_alias change but I guess it doesn't hurt?

2021-02-25 10:45 UTC, salimhb requested changes
This doesn't look like it covers all the points from https://github.com/railslove/recover-backlog/issues/91

>  Then I can use recover for free for a given time

Instead of setting `can_use_for_free`, I suggest simply extending the trial period to X days, where X is a property of Affiliate called `trial_days`

2021-02-25 10:45 UTC, salimhb commented on db/schema.rb
> +    t.string "menu_alias"
maybe it doesn't hurt to merge the change, but it also doesn't hurt to not do it ;)

2021-02-25 16:35 UTC, m0ppers commented on db/schema.rb
> +    t.string "menu_alias"
removed it

2021-02-28 20:18 UTC, m0ppers commented
ticket does the wrong thing just as salim noted :1st_place_medal: 
doing a new PR

2021-02-28 20:18 UTC, closed without merging