✨ add possibility to specify custom trial phase times per affiliate
railslove/rcvr-api pull request #63
Opened 2021-02-28 21:23 UTC by m0ppers

fixes https://github.com/railslove/recover-backlog/issues/91

2021-03-01 10:15 UTC, salimhb commented on app/controllers/devise_overwrites/registrations_controller.rb
> +      end
We should add a spec for this. It didn't have yet, but now that it has more business critical logic.

2021-03-01 10:15 UTC, salimhb commented on app/controllers/devise_overwrites/registrations_controller.rb
> +        resource.trial_ends_at = Time.now.advance(ActiveSupport::Duration.parse(affiliate.custom_trial_phase).parts)
How does this exactly work? At spec would give us examples.
However, we should show an example in RailsAdmin too?

2021-03-01 15:56 UTC, salimhb requested changes

2021-03-01 15:56 UTC, salimhb commented on spec/controllers/devise_overwrites/registrations_controller_spec.rb
> +        expect((2.weeks.since - trial_end).abs().seconds).to be < MAX_SECOND_TIME_DIFF
```suggestion
        expect(trial_end).to be_within(MAX_SECOND_TIME_DIFF.seconds).of(expected_trial_end)
```

2021-03-01 15:56 UTC, salimhb commented on spec/controllers/devise_overwrites/registrations_controller_spec.rb
> +        }.to raise_error(ActiveSupport::Duration::ISO8601Parser::ParsingError)
I'm concerned about this error blocking registration due to human error. We should validate input in rails admin.

2021-03-01 15:56 UTC, salimhb commented on app/controllers/devise_overwrites/registrations_controller.rb
> +        resource.trial_ends_at = Time.now.advance(ActiveSupport::Duration.parse(affiliate.custom_trial_phase).parts)
TIL ISO 8601 duration format :)
The comment is helpful. I suggest adding it to the help of the field in rails_admin. I don't know if our admins know this intuitively. There's also room for entering invalid text here, so it should be validated and better would be to also format its display in rails_admin.

2021-03-01 15:56 UTC, salimhb commented on spec/controllers/devise_overwrites/registrations_controller_spec.rb
> +end
Very well tested. Thanks 👍

2021-03-01 16:42 UTC, m0ppers commented on spec/controllers/devise_overwrites/registrations_controller_spec.rb
> +        expect((2.weeks.since - trial_end).abs().seconds).to be < MAX_SECOND_TIME_DIFF
I like the semantic but couldn't quite get it to work. The duration type seems to be somewhat special?

2021-03-01 16:43 UTC, m0ppers commented
should have flagged it as draft before ;) now it is ready I would say

2021-03-01 17:05 UTC, salimhb commented on spec/controllers/devise_overwrites/registrations_controller_spec.rb
> +        expect((2.weeks.since - trial_end).abs().seconds).to be < MAX_SECOND_TIME_DIFF
yes, you're comparing a `DateTime` with `ActiveSupport::TimeWithZone`, that's why. If you do `2.weeks.since.to_datetime`, it works.
Note that you're also declaring `expected_trial_end` and not using it.

2021-03-01 17:07 UTC, salimhb commented on spec/controllers/devise_overwrites/registrations_controller_spec.rb
> +  RSpec.describe RegistrationsController, type: :controller do
We're testing controllers using request specs. This controller is already being tested in `spec/requests/signup_spec.rb`. Please move these tests over there to stick to the same convention.

2021-03-01 17:09 UTC, salimhb commented on spec/controllers/devise_overwrites/registrations_controller_spec.rb
> +      @affiliate_with_1month_trial = create(:affiliate, { :custom_trial_phase => "P2M" })
It's not conventional to use instance variables in tests, please use `let` https://relishapp.com/rspec/rspec-core/v/3-10/docs/helper-methods/let-and-let

2021-03-02 08:26 UTC, m0ppers commented
ok I reworked it completely...can you have a look at it again @salimhb ? sorry I am just not a ruby developer :(

2021-03-02 09:19 UTC, salimhb approved these changes
![](https://media2.giphy.com/media/Tj4mYT6CucbjAgIkbY/giphy.gif)

2021-03-02 09:19 UTC, salimhb commented on spec/requests/signup_spec.rb
> +      affiliate_without_custom_trial_params
```suggestion
      params.deep_merge({ owner: { affiliate: affiliate_without_custom_trial.code } })
```

2021-03-02 09:19 UTC, salimhb commented on spec/requests/signup_spec.rb
> +      affiliate_with_2month_trial_params
```suggestion
      params.deep_merge({ owner: { affiliate: affiliate_with_2month_trial.code } })
```

2021-03-02 09:43 UTC, m0ppers commented on spec/requests/signup_spec.rb
> +      affiliate_without_custom_trial_params
thank you...I was searching for exactly this but it seemed to me that this was only possible by adding another gem...

2021-03-03 16:05 UTC, merged