Enables search through IRIS Tracing Portal
railslove/rcvr-api pull request #69
Opened 2021-03-17 23:58 UTC by hey-johnnypark

This enables step 1) of the integration with WFD Platform (now called IRIS+).

https://github.com/wirfuerdigitalisierung/documentation/blob/main/Implementierungsleitfaden.md#ressource-standortsuche

2021-03-18 13:09 UTC, salimhb requested changes

2021-03-18 13:09 UTC, salimhb commented on spec/helpers/iris/search_helper_spec.rb
> +end
delete unused spec

2021-03-18 13:09 UTC, salimhb commented on app/helpers/iris/search_helper.rb
> +      .joins(:owner).where("LOWER(companies.name) like LOWER(:search) OR LOWER(owners.company_name) like LOWER(:search)", search: "%#{search_string}%")
What about using Postgres Text Search? https://www.postgresql.org/docs/9.5/textsearch-tables.html#TEXTSEARCH-TABLES-SEARCH

2021-03-18 13:09 UTC, salimhb commented on app/helpers/iris/search_helper.rb
> +module Iris::SearchHelper
We're using [Interactors](https://github.com/collectiveidea/interactor) in this project. Better stick to the same pattern.

2021-03-18 20:15 UTC, hey-johnnypark commented on app/controllers/iris/iris_controller.rb
> +    if ENV['X_WFD_API_KEY'].nil? or ! ENV['X_WFD_API_KEY'].eql?(request.headers[@@WFD_API_KEY_HEADER]) then
Done

2021-03-18 20:16 UTC, hey-johnnypark commented on spec/helpers/iris/search_helper_spec.rb
> +end
Done

2021-03-18 20:19 UTC, hey-johnnypark commented on app/helpers/iris/search_helper.rb
> +      .joins(:owner).where("LOWER(companies.name) like LOWER(:search) OR LOWER(owners.company_name) like LOWER(:search)", search: "%#{search_string}%")
I am not aware of this so far. I think it works quite good as it is. Can we leave it for now because search might change to a push model where we push all our data to the portal.

2021-03-18 20:45 UTC, hey-johnnypark commented on app/helpers/iris/search_helper.rb
> +module Iris::SearchHelper
Moved to interactor

2021-03-19 09:39 UTC, salimhb requested changes

2021-03-19 09:39 UTC, salimhb commented on app/controllers/iris/iris_controller.rb
> +    if ! secure_compare(@@WFD_API_KEY, request.headers[@@WFD_API_KEY_HEADER] || '') then
```suggestion
    unless ActiveSupport::SecurityUtils.secure_compare(@@WFD_API_KEY, request.headers[@@WFD_API_KEY_HEADER] || '')
```

2021-03-19 09:39 UTC, salimhb commented on app/controllers/iris/iris_controller.rb
> +  include ActiveSupport::SecurityUtils
no need to include the whole thing :)

2021-03-19 10:01 UTC, salimhb commented
Looking at the implementation of [authenticate_or_request_with_http_token](https://github.com/rails/rails/blob/6d38553b093aeea26944ae75724f35011f7cc6b0/actionpack/lib/action_controller/metal/http_authentication.rb#L414), I can't help but feel that we are taking this too lightly. I don't like implementing my own security, when there is something already available and scrutinized 😞

2021-03-21 23:00 UTC, hey-johnnypark commented on app/controllers/iris/iris_controller.rb
> +  include ActiveSupport::SecurityUtils
Done

2021-03-22 11:20 UTC, salimhb approved these changes
![](https://media1.giphy.com/media/vgw9iixBqZJsI/giphy.gif)

2021-04-07 09:37 UTC, bitboxer commented
@hey-johnnypark  marked the issue as `invalid`. Marked the PR now, too. Please do not merge it.

2021-04-12 09:58 UTC, bitboxer commented
Closing because we will need to implement it a bit differently.

2021-04-12 09:58 UTC, closed without merging