6 edit personal checkin data
railslove/rcvr-api pull request #70
Opened 2021-03-18 22:09 UTC by hey-johnnypark

This is the backend implementation for when a guest changes its data. 

Highlights:

1) We use papertrail to keep a record of a ticket history.

2) For this similar to active storage we needed to change the relation data type to UUID. 

3) Everything is covered by tests.

2021-03-19 11:49 UTC, salimhb requested changes

2021-03-19 11:49 UTC, salimhb commented on db/schema.rb
> +    t.integer "auto_checkout_minutes"
Stop trolling @m0ppers 🤣 https://github.com/railslove/rcvr-api/pull/68

2021-03-21 23:15 UTC, hey-johnnypark commented on db/schema.rb
> +    t.integer "auto_checkout_minutes"
What should I do here @salimhb sorry I do not get it :)

2021-03-22 11:22 UTC, salimhb commented on db/schema.rb
> +    t.integer "auto_checkout_minutes"
Don't add this change. @m0ppers already fixed it for the **second** time in #68 😉

2021-04-06 12:55 UTC, salimhb approved these changes
![](https://media1.giphy.com/media/cNfdCiR00n8kCKeuhJ/giphy.gif)

2021-04-07 08:27 UTC, merged